//! Names that never return (ported from C++ `is_noreturn_name`).

const NORETURN: &[&str] = &[
    "exit",
    "_exit",
    "_Exit",
    "abort",
    "quick_exit",
    "ExitProcess",
    "ExitThread",
    "FreeLibraryAndExitThread",
    "FatalExit",
    "FatalAppExitA",
    "FatalAppExitW",
    "RtlExitUserProcess",
    "RtlExitUserThread",
    "__stack_chk_fail",
    "__stack_chk_fail_local",
    "__assert_fail",
    "__assert_rtn",
    "_assert",
    "_wassert",
    "__fortify_fail",
    "__chk_fail",
    "__libc_fatal",
    "longjmp",
    "_longjmp",
    "siglongjmp",
    "__longjmp_chk",
    "pthread_exit",
    "err",
    "errx",
    "verr",
    "verrx",
    "__cxa_throw",
    "__cxa_rethrow",
    "__cxa_bad_cast",
    "__cxa_bad_typeid",
    "__cxa_throw_bad_array_new_length",
    "_Unwind_Resume",
    "_CxxThrowException",
    "__std_terminate",
    "terminate",
    "_ZSt9terminatev",
    "__report_gsfailure",
    "_invalid_parameter_noinfo_noreturn",
    "_invoke_watson",
    "_ZSt17__throw_bad_allocv",
    "_ZSt20__throw_length_errorPKc",
    "_ZSt19__throw_logic_errorPKc",
    "_ZSt20__throw_out_of_rangePKc",
    "_ZSt24__throw_out_of_range_fmtPKcz",
    "_ZSt25__throw_bad_function_callv",
];

pub fn is_noreturn_name(name: &str) -> bool {
    NORETURN.iter().any(|&n| n == name)
}
